Lab08
MalexSw/Programming pull request #3
Opened 2024-11-22 18:58 UTC by MalexSw

Add Lab8

2024-11-23 15:11 UTC, volnsav requested changes
Please delete the binaries, review and add comments.

2024-11-23 15:11 UTC, volnsav commented on Lab08/main.c
> +
This is the wrong approach, you need to pass the array and its size as arguments.

2024-11-23 15:11 UTC, volnsav commented on Lab08/main.c
> +    int secondGreatest = minValue;
See the comment above.

2024-11-23 15:11 UTC, volnsav commented on Lab08/main.c
> +    int valForModification = 3;
See the comment above

2024-11-23 15:11 UTC, volnsav commented on Lab08/main.c
> +    int mergedArray[2 * numberOfElements];
See the comment above

2024-11-23 15:11 UTC, volnsav commented on Lab08/main.c
> +    int oddCount = 0;
see the comment abobe

2024-11-26 20:17 UTC, closed without merging

2024-11-26 20:17 UTC, MalexSw commented
Changes are made